sudo: required
dist: trusty
language: cpp

addons:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - gcovr

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: COMPILER=clang++-3.8

before_install:
  - sudo apt-get update -qq

before_script:
  - export CXX=$COMPILER
  - $CXX --version

script:
  - make

after_success:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)
