sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcovr
      after_success:
        - make coverage
        - bash <(curl -s https://codecov.io/bash)

    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8

    - os: osx
      compiler: clang
      env: COMPILER=clang++
      osx_image: xcode8.2

before_install:
  # Workaround for --push-state error when linking unit_tests
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:jonathonf/binutils --yes || true;
      sudo apt-get update -qq --yes || true;
      sudo apt-get install -qq --yes --force-yes binutils;
    fi

before_script:
  - export CXX=$COMPILER
  - $CXX --version

script:
  - make


