SRC = $(wildcard *.cpp *.c)
OBJ = $(SRC:.cpp=.cpp.o)
OBJ := $(OBJ:.c=.c.o)

all: $(OBJ)

$(OBJ): clean

%.cpp.o: %.cpp
	$(CXX) -c -o $@ $<

%.c.o: %.c
	$(CC) -c -o $@ $<

clean:
	rm -f *.o

dbg-%:
	@echo "Makefile: Value of $* = $($*)"

.PHONY: clean