SRC = $(wildcard *.cpp *.c)
OBJ = $(SRC:.cpp=.cpp.o)
OBJ := $(OBJ:.c=.c.o)
DEP = $(OBJ:.o=.d)

all: clean $(OBJ)

$(OBJ): clean

%.cpp.o: %.cpp
	$(CXX) -M $< -MF $@
	$(CXX) -MM $< -MF $@
	$(CXX) -MD $< -MF $@
	$(CXX) -MMD $< -MF $@
	$(CXX) -c -o $@ $<

%.c.o: %.c
	$(CC) -M $< -MF $@
	$(CC) -MM $< -MF $@
	$(CC) -MD $< -MF $@
	$(CC) -MMD $< -MF $@
	$(CC) -c -o $@ $<

clean:
	rm -f *.o *.d

dbg-%:
	@echo "Makefile: Value of $* = $($*)"

.PHONY: clean