[
    {
        "command": "g++ test_source1.cpp -c -o cpp.o",
        "directory": "$PWD/src",
        "file": "$PWD/src/test_source1.cpp"
    },
    {
        "command": "g++ test_source2.cpp -c -o cpp.o",
        "directory": "$PWD/src",
        "file": "$PWD/src/test_source2.cpp"
    },
    {
        "command": "g++ test_source3.cpp -c -o cpp.o",
        "directory": "$PWD/src",
        "file": "$PWD/src/test_source3.cpp"
    },
    {
        "command": "g++ test_source4.cpp -c -o cpp.o",
        "directory": "$PWD/src",
        "file": "$PWD/src/test_source4.cpp"
    },
    {
        "command": "gcc test_source5.c -c -o c.o",
        "directory": "$PWD/src",
        "file": "$PWD/src/test_source5.c"
    },
    {
        "command": "gcc test_source6.c -c -o c.o",
        "directory": "$PWD/src",
        "file": "$PWD/src/test_source6.c"
    },
    {
        "command": "gcc test_source7.c -c -o c.o",
        "directory": "$PWD/src",
        "file": "$PWD/src/test_source7.c"
    },
    {
        "command": "gcc test_source8.c -c -o c.o",
        "directory": "$PWD/src",
        "file": "$PWD/src/test_source8.c"
    }
]